from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path('', views.index, name='index'),
    path("mensagens/",views.ajax_mensagens,name="ajax_mensagens"),
    path("ajax/apresentadores/", views.ajax_listar_apresentadores, name="ajax_listar_apresentadores"),
    path("apresentadores/", views.apresentadores, name="apresentadores"),
    path("apresentadores/novo/", views.apresentador_novo, name="apresentador_novo"),
    path("apresentadores/<int:id_apresentador>/editar/", views.apresentador_editar, name="apresentador_editar"),
    path("apresentadores/<int:id_apresentador>/remover/", views.apresentador_remover, name="apresentador_remover"),
    path("apresentadores/<int:id_apresentador>/detalhar/", views.apresentador_detalhar, name="apresentador_detalhar"),
    path('programas/', views.programas, name='programas'),
    path("programas/ajax/", views.ajax_listar_programas, name="ajax_listar_programas"),
    path('programas/novo/', views.programa_novo, name='programa_novo'),
    path('programas/<int:id_programa>/', views.programas, name='programa'),
    path('programas/<int:id_programa>/editar/', views.programa_editar, name='programa_editar'),
    path('programas/remover/<int:id_programa>/', views.programa_remover, name='programa_remover'),
    path('programas/detalhar/<int:id_programa>/', views.programa_detalhar, name='programa_detalhar'),
    path("ajax/programacao/", views.ajax_listar_programacoes, name="ajax_listar_programacoes"),
    path('programacao/', views.programacao, name='programacao'),
    path('programacao/<int:id_programacao>/', views.programacao, name='programacao'),
    path('programacao/novo/', views.programacao_novo, name='programacao_novo'),
    path('programacao/<int:id_item>/editar/', views.programacao_editar, name='programacao_editar'),
    path('programacao/<int:id_item>/remover/', views.programacao_remover, name='programacao_remover'),
    path("ajax/episodios/", views.ajax_listar_episodios, name="ajax_listar_episodios"),
    path("programas/<int:id_programa>/episodios/ajax/",views.ajax_listar_episodios_programa,name="ajax_listar_episodios_programa"),    path('episodios/', views.episodios, name='episodios'),
    path('episodios/novo/<int:id_programa>/', views.episodio_novo, name='episodio_novo'),
    path('episodios/<int:id_item>/editar/', views.episodio_editar, name='episodio_editar'),
    path('episodios/<int:id_item>/remover/', views.episodio_remover, name='episodio_remover'),
    path('programas/<int:id_programa>/episodios/', views.detalhar_episodio,name='episodios_programa'),
    path("curtidos/",views.meus_curtidos,name="curtidos"),
    path("curtidos/ajax/",views.ajax_listar_curtidos,name="ajax_listar_curtidos"),
    path("sugestoes/",views.view_sugestoes,name="sugestoes"),
    path("sugestoes/ajax/",views.ajax_listar_sugestoes,name="ajax_listar_sugestoes"),
    path("sugestoes/remover/<int:id_item>/",views.sugestoes_remover,name="sugestoes_remover"),
    path("pedidos/",views.view_pedidos,name="pedidos"),
    path("pedidos/ajax/",views.ajax_listar_pedidos,name="ajax_listar_pedidos"),
    path("pedidos/remover/<int:id_item>/",views.pedidos_remover,name="pedidos_remover"),
    path("perfil/",views.perfil,name="perfil"),    
    path("perfil/editar/", views.editar_perfil, name="editar_perfil"),
]