# Generated by Django 5.2.6 on 2025-11-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='radio/usuarios/perfil/'),
        ),
    ]
