# Generated by Django 5.2.7 on 2026-01-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='apresentadores/')),
                ('descricao', models.CharField(max_length=1000)),
                ('idade', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Apresentadores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Seu nome')),
                ('musica', models.CharField(max_length=1000, verbose_name='O que você gostaria de ouvir hoje?')),
                ('artista', models.CharField(max_length=1000, verbose_name='Qual o nome do(a) artista ou banda dessa música?')),
                ('horario_desejado', models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], max_length=5, verbose_name='Qual o horário desejado?')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Observações (opcional)')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'Seg'), ('terca', 'Ter'), ('quarta', 'Qua'), ('quinta', 'Qui'), ('sexta', 'Sex')], max_length=10)),
                ('horario', models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'programação',
            },
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Seu nome')),
                ('comentario', models.TextField(verbose_name='Quais os programas você gostaria de encontrar na nossa rádio?')),
            ],
            options={
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_episodio', models.ImageField(blank=True, null=True, upload_to='img_episodio/', verbose_name='Banner do episodio')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('audio', models.URLField(blank=True, null=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('apresentador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios', to='radio.apresentador')),
            ],
            options={
                'verbose_name_plural': 'Episodios',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_programa', models.ImageField(blank=True, null=True, upload_to='img_programa/', verbose_name='Banner do programa')),
                ('nome_programa', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('descricao_programa', models.CharField(max_length=1000, verbose_name='Descrição do programa')),
                ('apresentador_programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='radio.apresentador')),
            ],
            options={
                'verbose_name_plural': 'programas',
            },
        ),
    ]
