# Generated by Django 5.2.6 on 2025-12-01 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_home', models.CharField(max_length=100)),
                ('subtitulo_home', models.CharField(max_length=200)),
                ('bg_home', models.ImageField(blank=True, upload_to='radio/banner_home/')),
                ('quemsomos_home', models.CharField(max_length=1000)),
                ('nome', models.CharField(blank=True, max_length=50, verbose_name='Seu nome')),
                ('comentario', models.TextField(blank=True, max_length=1000, verbose_name='Quais os programas você gostaria de encontrar na nossa rádio?')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Seu nome')),
                ('musica', models.CharField(max_length=1000, verbose_name='O que você gostaria de ouvir hoje?')),
                ('artista', models.CharField(max_length=1000, verbose_name='Qual o nome do(a) artista ou banda dessa música?')),
                ('horario_desejado', models.TimeField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], verbose_name='Qual o horário desejado?')),
                ('mensagem', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações (opcional)')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sobre', models.CharField(max_length=100)),
                ('subtitulo_sobre', models.CharField(max_length=1000)),
                ('conteudo_sobre', models.CharField(max_length=1000)),
                ('banner_sobre', models.ImageField(upload_to='banner_sobre/')),
            ],
            options={
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_programa', models.ImageField(blank=True, upload_to='radio/img_programa/', verbose_name='Banner do programa')),
                ('nome_programa', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('descricao_programa', models.CharField(max_length=1000, verbose_name='Descrição do programa')),
                ('apresentador_programa', models.CharField(max_length=1000, verbose_name='Apresentador do programa')),
                ('curtidas', models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('apresentador', models.CharField(max_length=1000, null=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='radio.programa')),
            ],
            options={
                'verbose_name_plural': 'Episodios',
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'Seg'), ('terca', 'Ter'), ('quarta', 'Qua'), ('quinta', 'Qui'), ('sexta', 'Sex')], max_length=10)),
                ('horario', models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')])),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.programa')),
            ],
            options={
                'verbose_name_plural': 'programação',
            },
        ),
    ]
