# Generated by Django 5.2.6 on 2025-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_home', models.CharField(max_length=100)),
                ('subtitulo_home', models.CharField(max_length=200)),
                ('bg_home', models.ImageField(blank=True, upload_to='radio/banner_home/')),
                ('quemsomos_home', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_podcast', models.ImageField(blank=True, upload_to='radio/img_podcast/')),
                ('nome_podcast', models.CharField(max_length=100)),
                ('descricao_podcast', models.CharField(max_length=100)),
                ('host_podcast', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_programa', models.ImageField(blank=True, upload_to='radio/img_programa/')),
                ('nome_programa', models.CharField(max_length=100)),
                ('descricao_programa', models.CharField(max_length=100)),
                ('artista_programa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_programação', models.ImageField(blank=True, upload_to='radio/img_programacao/')),
                ('titulo_programacao', models.CharField(max_length=100)),
                ('horario_programacao', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sobre', models.CharField(max_length=100)),
                ('subtitulo_sobre', models.CharField(max_length=150)),
                ('conteudo_sobre', models.CharField(max_length=150)),
                ('banner_sobre', models.ImageField(upload_to='banner_sobre/')),
            ],
        ),
    ]
