# Generated by Django 5.2.6 on 2025-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='programacao',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
