# Generated by Django 5.2.6 on 2025-10-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name_plural': 'Programações'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name_plural': 'Sobre'},
        ),
    ]
