# Generated by Django 5.2.7 on 2025-12-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodio',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='radio.programa'),
        ),
        migrations.AddField(
            model_name='programacao',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.programa'),
        ),
    ]
