# Generated by Django 5.2.7 on 2025-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_desejado',
            field=models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], max_length=5, verbose_name='Qual o horário desejado?'),
        ),
    ]
