# Generated by Django 5.2.6 on 2025-12-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_programacao_data_fim_programacao_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='data_inicio',
        ),
    ]
