# Generated by Django 5.2.7 on 2025-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_home_options_alter_podcast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta')], max_length=10),
        ),
    ]
