# Generated by Django 5.2.7 on 2025-12-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_pedido_horario_desejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.TextField(max_length=1000, verbose_name='Seu nome'),
        ),
    ]
