# Generated by Django 5.2.7 on 2026-01-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apresentador',
            name='idade',
        ),
    ]
