# Generated by Django 5.2.7 on 2025-12-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_alter_pedido_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='comentario',
            field=models.TextField(max_length=1000, verbose_name='Quais os programas você gostaria de encontrar na nossa rádio?'),
        ),
        migrations.AlterField(
            model_name='home',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Seu nome'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=1000, verbose_name='Seu nome'),
        ),
    ]
