# Generated by Django 5.2.7 on 2025-10-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_programacao_dia_semana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacao',
            old_name='bg_programação',
            new_name='bg_programacao',
        ),
    ]
