# Generated by Django 5.2.7 on 2025-12-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_remove_programacao_data_fim_and_more'),
        ('radio', '0004_alter_home_comentario_alter_home_nome_and_more'),
    ]

    operations = [
    ]
