# Generated by Django 5.2.6 on 2025-10-26 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_rename_bg_programação_programacao_bg_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.programa'),
        ),
    ]
