# Generated by Django 5.2.6 on 2026-02-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
