# Generated by Django 5.2.6 on 2025-10-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_programacao_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.podcast'),
        ),
    ]
