# Generated by Django 5.2.7 on 2025-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_merge_20251201_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Seu nome')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Quais os programas você gostaria de encontrar na nossa rádio?')),
            ],
            options={
                'verbose_name_plural': 'Sugestões',
            },
        ),
        migrations.RemoveField(
            model_name='home',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='home',
            name='nome',
        ),
    ]
