# Generated by Django 5.2.7 on 2025-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_programacao_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Seu nome')),
                ('musica', models.CharField(max_length=100, verbose_name='O que você gostaria de ouvir hoje?')),
                ('artista', models.CharField(max_length=100, verbose_name='Qual o nome do(a) artista ou banda dessa música?')),
                ('horario_desejado', models.TimeField(verbose_name='Qual o horário desejado?')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Observações (opcional)')),
                ('horario_pedidos', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
