# Generated by Django 5.2.7 on 2025-12-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_sugestao_remove_home_comentario_remove_home_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
