# Generated by Django 5.2.7 on 2025-12-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
