# Generated by Django 5.2.7 on 2025-10-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_pedidos',
            field=models.DateTimeField(default='12:00'),
        ),
    ]
