# Generated by Django 5.2.7 on 2025-12-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_delete_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='banner_episodio',
            field=models.ImageField(blank=True, upload_to='radio/img_episodio/', verbose_name='Banner do episodio'),
        ),
    ]
