# Generated by Django 5.2.7 on 2025-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_alter_pedido_horario_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_pedidos',
            field=models.TimeField(),
        ),
    ]
