# Generated by Django 5.2.7 on 2025-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_episodio_banner_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='audio',
            field=models.URLField(blank=True),
        ),
    ]
