# Generated by Django 5.2.7 on 2025-12-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_episodio_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='horario',
            field=models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], max_length=20),
        ),
    ]
