# Generated by Django 5.2.7 on 2025-10-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_alter_pedido_horario_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='horario_pedidos',
        ),
    ]
