# Generated by Django 5.2.7 on 2025-10-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_remove_pedido_horario_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.podcast'),
        ),
    ]
