# Generated by Django 5.2.7 on 2025-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_alter_programacao_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='banner_episodio',
            field=models.ImageField(blank=True, upload_to='img_episodio/', verbose_name='Banner do episodio'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='banner_programa',
            field=models.ImageField(blank=True, upload_to='img_programa/', verbose_name='Banner do programa'),
        ),
    ]
