# Generated by Django 5.2.6 on 2025-11-02 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_alter_programacao_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='bg_programacao',
        ),
        migrations.AlterField(
            model_name='programacao',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.programa'),
        ),
    ]
