# Generated by Django 5.2.7 on 2025-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_remove_programacao_bg_programacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Quais programas você gostaria de encontrar na nossa rádio?'),
        ),
        migrations.AddField(
            model_name='home',
            name='nome',
            field=models.CharField(blank=True, max_length=30, verbose_name='Seu nome'),
        ),
    ]
