# Generated by Django 5.2.7 on 2025-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_home_comentario_home_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, null=True, verbose_name='Turno'),
        ),
    ]
