# Generated by Django 5.2.7 on 2025-11-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_pedido_turno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programa',
            new_name='Quadro',
        ),
        migrations.AlterModelOptions(
            name='quadro',
            options={'verbose_name_plural': 'Quadros'},
        ),
        migrations.RenameField(
            model_name='programacao',
            old_name='programa',
            new_name='quadro',
        ),
        migrations.RenameField(
            model_name='quadro',
            old_name='artista_programa',
            new_name='artista_quadro',
        ),
        migrations.RenameField(
            model_name='quadro',
            old_name='banner_programa',
            new_name='banner_quadro',
        ),
        migrations.RenameField(
            model_name='quadro',
            old_name='descricao_programa',
            new_name='descricao_quadro',
        ),
        migrations.RenameField(
            model_name='quadro',
            old_name='nome_programa',
            new_name='nome_quadro',
        ),
    ]
