# Generated by Django 5.2.6 on 2025-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_rename_programa_quadro_alter_quadro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadro',
            name='artista_quadro',
            field=models.CharField(max_length=100, verbose_name='Artista do quadro'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='banner_quadro',
            field=models.ImageField(blank=True, upload_to='radio/img_programa/', verbose_name='Banner do quadro'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='descricao_quadro',
            field=models.CharField(max_length=100, verbose_name='Descrição do quadro'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='nome_quadro',
            field=models.CharField(max_length=100, verbose_name='Nome do quadro'),
        ),
    ]
