# Generated by Django 5.2.7 on 2025-11-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_alter_quadro_artista_quadro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Seu nome'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quemsomos_home',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='artista',
            field=models.CharField(max_length=1000, verbose_name='Qual o nome do(a) artista ou banda dessa música?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mensagem',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações (opcional)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='musica',
            field=models.CharField(max_length=1000, verbose_name='O que você gostaria de ouvir hoje?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=1000, verbose_name='Seu nome'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='descricao_podcast',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='host_podcast',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='artista_quadro',
            field=models.CharField(max_length=1000, verbose_name='Artista do quadro'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='descricao_quadro',
            field=models.CharField(max_length=1000, verbose_name='Descrição do quadro'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='conteudo_sobre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='subtitulo_sobre',
            field=models.CharField(max_length=1000),
        ),
    ]
