# Generated by Django 5.2.6 on 2025-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0018_alter_home_nome_alter_home_quemsomos_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Quais os quadros você gostaria de encontrar na nossa rádio?'),
        ),
    ]
