# Generated by Django 5.2.7 on 2025-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0019_alter_home_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_programa', models.ImageField(blank=True, upload_to='radio/img_programa/', verbose_name='Banner do programa')),
                ('nome_programa', models.CharField(max_length=100, verbose_name='Nome do programa')),
                ('descricao_programa', models.CharField(max_length=1000, verbose_name='Descrição do programa')),
                ('apresentador_programa', models.CharField(max_length=1000, verbose_name='Apresentador do programa')),
                ('horario_programa', models.TimeField()),
                ('dia_semana', models.CharField(blank=True, choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='quadro',
        ),
        migrations.AlterField(
            model_name='home',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Quais os programas você gostaria de encontrar na nossa rádio?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_desejado',
            field=models.TimeField(choices=[('08:30', '08:30'), ('10:20', '10,20'), ('14:30', '14:30'), ('16:20', '16:20')], verbose_name='Qual o horário desejado?'),
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
        migrations.DeleteModel(
            name='Quadro',
        ),
    ]
