# Generated by Django 5.2.7 on 2025-11-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0020_programa_remove_programacao_podcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario_desejado',
            field=models.TimeField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')], verbose_name='Qual o horário desejado?'),
        ),
    ]
