# Generated by Django 5.2.7 on 2025-11-15 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_alter_pedido_horario_desejado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='horario_programa',
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta')], max_length=10)),
                ('horario', models.TimeField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')])),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.programa')),
            ],
        ),
    ]
