# Generated by Django 5.2.7 on 2025-11-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0022_remove_programa_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='dia',
            field=models.CharField(choices=[('segunda', 'Seg'), ('terca', 'Ter'), ('quarta', 'Qua'), ('quinta', 'Qui'), ('sexta', 'Sex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='programacao',
            name='horario',
            field=models.CharField(choices=[('08:30', '08:30 - 08:50'), ('10:20', '10:20 - 10:30'), ('14:30', '14:30 - 14:50'), ('16:20', '16:20 - 16:30')]),
        ),
    ]
