# Generated by Django 5.2.7 on 2025-11-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0023_alter_programacao_dia_alter_programacao_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name_plural': 'programação'},
        ),
    ]
