# Generated by Django 5.2.6 on 2025-11-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0024_alter_programacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('view_dashboard', 'Pode acessar o dashboard')]},
        ),
    ]
