# Generated by Django 5.2.6 on 2025-11-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0025_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
    ]
