# Generated by Django 5.2.6 on 2025-11-23 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0026_alter_pedido_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='curtidas',
            field=models.ManyToManyField(related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
