# Generated by Django 5.2.7 on 2025-11-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0028_alter_programa_curtidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('audio', models.FileField(upload_to='radio/episodios/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='radio.programa')),
            ],
            options={
                'verbose_name_plural': 'Episodios',
            },
        ),
    ]
