# Generated by Django 5.2.7 on 2025-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0029_episodio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='audio',
        ),
        migrations.AddField(
            model_name='episodio',
            name='apresentador',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
